export default{
  "code": 1,
  "data": {
    "count": 8,
    "list": [{
      "id": "11217",
      "twoId": 11215,
      "name": "君度可可",
      "french": "Choco Cointreau",
      "price": "298.00",
      "tid": 0,
      "tname": "",
      "timg": "",
      "chineseBrief": "甜与苦从来不是对立，因为巧克力，更因为君度力娇\n浓烈而温和，清凉却温暖，苦涩带甘甜的味觉冲击\n滋味的美妙融合，丰富而立体\n君度可可，只为呈现跨越时光的味道",
      "fid": "37",
      "fname": "巧克力",
      "saleTotal": 9739,
      "pprice": "298.00",
      "img": "https:\/\/static.mcake.com\/goods\/jundukeke\/M0601\/list\/1.jpg",
      "sku": "M0602",
      "spec": "2磅",
      "limg": "https:\/\/static.mcake.com\/withwheat\/list\/M0602.jpg",
      "list": [{
        "id": 11216,
        "sku": "M0601",
        "ahead": "提前5小时预定",
        "edible": "2-3人食",
        "spec": "1磅",
        "price": "198.00",
        "size": "15cm*4.0cm",
        "pprice": "198.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/jundukeke\/M0601",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }, {
        "id": 11217,
        "sku": "M0602",
        "ahead": "提前5小时预定",
        "edible": "4-7人食",
        "spec": "2磅",
        "price": "298.00",
        "size": "20cm*4.0cm",
        "pprice": "298.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/jundukeke\/M0601",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }]
    }, {
      "id": "11129",
      "twoId": 11127,
      "name": "沙布蕾芭菲",
      "french": "Sablé parfait",
      "price": "298.00",
      "tid": 0,
      "tname": "",
      "timg": "",
      "chineseBrief": "法式传统沙布蕾饼，搭配马达加斯加香草芭菲和熔岩巧克力，入口即化，形成绝佳口感。",
      "fid": "37",
      "fname": "巧克力",
      "saleTotal": 15668,
      "pprice": "298.00",
      "img": "https:\/\/static.mcake.com\/goods\/shabuleibafei\/Z0202\/list\/1.jpg",
      "sku": "z0202",
      "spec": "2磅",
      "limg": "https:\/\/static.mcake.com\/withwheat\/list\/z0202.jpg",
      "list": [{
        "id": 11128,
        "sku": "z0201",
        "ahead": "提前5小时预定",
        "edible": "2-3人食",
        "spec": "1磅",
        "price": "198.00",
        "size": "16cm*10cm*5cm",
        "pprice": "198.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/shabuleibafei\/Z0202",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }, {
        "id": 11129,
        "sku": "z0202",
        "ahead": "提前5小时预定",
        "edible": "4-7人食",
        "spec": "2磅",
        "price": "298.00",
        "size": "23cm*14cm*5cm",
        "pprice": "298.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/shabuleibafei\/Z0202",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }, {
        "id": 11130,
        "sku": "z0203",
        "ahead": "提前24小时预定",
        "edible": "8-12人食",
        "spec": "3磅",
        "price": "428.00",
        "size": "28cm*18cm*5cm",
        "pprice": "428.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/shabuleibafei\/Z0202",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }, {
        "id": 11131,
        "sku": "z0205",
        "ahead": "提前24小时预定",
        "edible": "12-20人食",
        "spec": "5磅",
        "price": "728.00",
        "size": "36cm*22cm*5cm",
        "pprice": "728.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/shabuleibafei\/Z0202",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }]
    }, {
      "id": "11224",
      "twoId": 11222,
      "name": "巧克力黑兰",
      "french": "Lotus Noir",
      "price": "298.00",
      "tid": 0,
      "tname": "",
      "timg": "",
      "chineseBrief": "这是法国白兰地的一次重生\n以另一种脱胎换骨的形式，加上比利时黑巧克力的爽滑\n借着时间的指针，在舌尖，在心间，画出微醺的轨迹",
      "fid": "37",
      "fname": "巧克力",
      "saleTotal": 12178,
      "pprice": "298.00",
      "img": "https:\/\/img.mcake.com\/goods\/20170615\/1933\/list_1933_1.jpg",
      "sku": "J0102",
      "spec": "2磅",
      "limg": "https:\/\/static.mcake.com\/withwheat\/list\/J0102.jpg",
      "list": [{
        "id": 11223,
        "sku": "J0101",
        "ahead": "提前5小时预定",
        "edible": "2-3人食",
        "spec": "1磅",
        "price": "198.00",
        "size": "16cm*10cm*4.8cm",
        "pprice": "198.00",
        "pic": {
          "url": "https:\/\/img.mcake.com\/goods\/",
          "list": [{
            "b": "20170615\/1933\/big_1933_1.jpg",
            "m": "20170615\/1933\/middle_1933_1.jpg",
            "s": "20170615\/1933\/small_1933_1.jpg"
          }, {
            "b": "20170615\/1933\/big_1933_2.jpg",
            "m": "20170615\/1933\/middle_1933_2.jpg",
            "s": "20170615\/1933\/small_1933_2.jpg"
          }, {
            "b": "20170615\/1933\/big_1933_3.jpg",
            "m": "20170615\/1933\/middle_1933_3.jpg",
            "s": "20170615\/1933\/small_1933_3.jpg"
          }]
        }
      }, {
        "id": 11224,
        "sku": "J0102",
        "ahead": "提前5小时预定",
        "edible": "4-7人食",
        "spec": "2磅",
        "price": "298.00",
        "size": "23cm*14cm*5cm",
        "pprice": "298.00",
        "pic": {
          "url": "https:\/\/img.mcake.com\/goods\/",
          "list": [{
            "b": "20170615\/1933\/big_1933_1.jpg",
            "m": "20170615\/1933\/middle_1933_1.jpg",
            "s": "20170615\/1933\/small_1933_1.jpg"
          }, {
            "b": "20170615\/1933\/big_1933_2.jpg",
            "m": "20170615\/1933\/middle_1933_2.jpg",
            "s": "20170615\/1933\/small_1933_2.jpg"
          }, {
            "b": "20170615\/1933\/big_1933_3.jpg",
            "m": "20170615\/1933\/middle_1933_3.jpg",
            "s": "20170615\/1933\/small_1933_3.jpg"
          }]
        }
      }, {
        "id": 11225,
        "sku": "J0103",
        "ahead": "提前24小时预定",
        "edible": "8-12人食",
        "spec": "3磅",
        "price": "428.00",
        "size": "28cm*18cm*4.8cm",
        "pprice": "428.00",
        "pic": {
          "url": "https:\/\/img.mcake.com\/goods\/",
          "list": [{
            "b": "20170615\/1933\/big_1933_1.jpg",
            "m": "20170615\/1933\/middle_1933_1.jpg",
            "s": "20170615\/1933\/small_1933_1.jpg"
          }, {
            "b": "20170615\/1933\/big_1933_2.jpg",
            "m": "20170615\/1933\/middle_1933_2.jpg",
            "s": "20170615\/1933\/small_1933_2.jpg"
          }, {
            "b": "20170615\/1933\/big_1933_3.jpg",
            "m": "20170615\/1933\/middle_1933_3.jpg",
            "s": "20170615\/1933\/small_1933_3.jpg"
          }]
        }
      }, {
        "id": 11226,
        "sku": "J0105",
        "ahead": "提前24小时预定",
        "edible": "12-20人食",
        "spec": "5磅",
        "price": "728.00",
        "size": "36cm*22cm*5cm",
        "pprice": "728.00",
        "pic": {
          "url": "https:\/\/img.mcake.com\/goods\/",
          "list": [{
            "b": "20170615\/1933\/big_1933_1.jpg",
            "m": "20170615\/1933\/middle_1933_1.jpg",
            "s": "20170615\/1933\/small_1933_1.jpg"
          }, {
            "b": "20170615\/1933\/big_1933_2.jpg",
            "m": "20170615\/1933\/middle_1933_2.jpg",
            "s": "20170615\/1933\/small_1933_2.jpg"
          }, {
            "b": "20170615\/1933\/big_1933_3.jpg",
            "m": "20170615\/1933\/middle_1933_3.jpg",
            "s": "20170615\/1933\/small_1933_3.jpg"
          }]
        }
      }]
    }, {
      "id": "11467",
      "twoId": 11453,
      "name": "黑森林拿破仑",
      "french": "La Forêt noir",
      "price": "298.00",
      "tid": 0,
      "tname": "",
      "timg": "",
      "chineseBrief": "久负盛名的黑森林蛋糕遇上拿破仑酥皮，微苦与松脆，浓香丰满。融合樱桃的清爽、奶油的甜，带思绪飘往北地黑森林。",
      "fid": "37",
      "fname": "巧克力",
      "saleTotal": 14595,
      "pprice": "298.00",
      "img": "https:\/\/static.mcake.com\/goods\/heisenlinnapolun\/N0605\/list\/1.jpg",
      "sku": "N0602",
      "spec": "2磅",
      "limg": "https:\/\/static.mcake.com\/withwheat\/list\/N0602.jpg",
      "list": [{
        "id": 11466,
        "sku": "N0601",
        "ahead": "提前5小时预定",
        "edible": "2-3人食",
        "spec": "1磅",
        "price": "198.00",
        "size": "17cm*11cm*8cm",
        "pprice": "198.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/heisenlinnapolun\/N0605",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }, {
        "id": 11467,
        "sku": "N0602",
        "ahead": "提前5小时预定",
        "edible": "4-7人食",
        "spec": "2磅",
        "price": "298.00",
        "size": "24cm*15cm*8cm",
        "pprice": "298.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/heisenlinnapolun\/N0605",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }, {
        "id": 11468,
        "sku": "N0603",
        "ahead": "提前5小时预定",
        "edible": "8-12人食",
        "spec": "3磅",
        "price": "428.00",
        "size": "29cm*19cm*8cm",
        "pprice": "428.00",
        "pic": {
          "url": "https:\/\/img.mcake.com\/goods\/",
          "list": [{
            "b": "20151015\/2103\/big_2103_1.jpg",
            "m": "20151015\/2103\/middle_2103_1.jpg",
            "s": "20151015\/2103\/small_2103_1.jpg"
          }, {
            "b": "20151015\/2103\/big_2103_2.jpg",
            "m": "20151015\/2103\/middle_2103_2.jpg",
            "s": "20151015\/2103\/small_2103_2.jpg"
          }, {
            "b": "20151015\/2103\/big_2103_3.jpg",
            "m": "20151015\/2103\/middle_2103_3.jpg",
            "s": "20151015\/2103\/small_2103_3.jpg"
          }]
        }
      }, {
        "id": 11469,
        "sku": "N0605",
        "ahead": "提前5小时预定",
        "edible": "12-20人食",
        "spec": "5磅",
        "price": "728.00",
        "size": "37cm*23cm*8cm",
        "pprice": "728.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/heisenlinnapolun\/N0605",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }]
    }, {
      "id": "11243",
      "twoId": 11241,
      "name": "天使巧克力",
      "french": "Gâteau des anges",
      "price": "298.00",
      "tid": 0,
      "tname": "",
      "timg": "",
      "chineseBrief": "用巴黎的慵懒与浪漫\/\n精心制作出让天使都会爱上的美丽",
      "fid": "37",
      "fname": "巧克力",
      "saleTotal": 7028,
      "pprice": "298.00",
      "img": "https:\/\/static.mcake.com\/goods\/tianshiqiaokeli\/Q0302\/list\/1.jpg",
      "sku": "q0302",
      "spec": "2磅",
      "limg": "https:\/\/static.mcake.com\/withwheat\/list\/q0302.jpg",
      "list": [{
        "id": 11242,
        "sku": "q0301",
        "ahead": "提前5小时预定",
        "edible": "2-3人食",
        "spec": "1磅",
        "price": "198.00",
        "size": "16cm*10cm*5cm",
        "pprice": "198.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/tianshiqiaokeli\/Q0302",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }, {
        "id": 11243,
        "sku": "q0302",
        "ahead": "提前5小时预定",
        "edible": "4-7人食",
        "spec": "2磅",
        "price": "298.00",
        "size": "23cm*14cm*5cm",
        "pprice": "298.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/tianshiqiaokeli\/Q0302",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }, {
        "id": 11244,
        "sku": "q0303",
        "ahead": "提前5小时预定",
        "edible": "8-12人食",
        "spec": "3磅",
        "price": "428.00",
        "size": "28cm*18cm*5cm",
        "pprice": "428.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/tianshiqiaokeli\/Q0302",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }, {
        "id": 11245,
        "sku": "q0305",
        "ahead": "提前5小时预定",
        "edible": "12-20人食",
        "spec": "5磅",
        "price": "728.00",
        "size": "36cm*22cm*5.5cm",
        "pprice": "728.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/tianshiqiaokeli\/Q0302",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }]
    }, {
      "id": "11237",
      "twoId": 11235,
      "name": "魔鬼巧克力",
      "french": "Diable chocolat",
      "price": "298.00",
      "tid": 0,
      "tname": "",
      "timg": "",
      "chineseBrief": "MCAKE\/将艺术气质渗入蛋糕制作环节\/\n每一款作品表层\/都被赋予千变万化的笔触\/\n当你收到的时候\/绝不需要担心“撞衫”的危险",
      "fid": "37",
      "fname": "巧克力",
      "saleTotal": 7145,
      "pprice": "298.00",
      "img": "https:\/\/static.mcake.com\/goods\/moguiqiaokeli\/Q0201\/list\/1.jpg",
      "sku": "q0202",
      "spec": "2磅",
      "limg": "https:\/\/static.mcake.com\/withwheat\/list\/q0202.jpg",
      "list": [{
        "id": 11236,
        "sku": "q0201",
        "ahead": "提前5小时预定",
        "edible": "2-3人食",
        "spec": "1磅",
        "price": "198.00",
        "size": "16cm*10cm*4.5cm",
        "pprice": "198.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/moguiqiaokeli\/Q0201",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }, {
        "id": 11237,
        "sku": "q0202",
        "ahead": "提前5小时预定",
        "edible": "4-7人食",
        "spec": "2磅",
        "price": "298.00",
        "size": "23cm*14cm*4.5cm",
        "pprice": "298.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/moguiqiaokeli\/Q0201",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }, {
        "id": 11238,
        "sku": "q0203",
        "ahead": "提前5小时预定",
        "edible": "8-12人食",
        "spec": "3磅",
        "price": "428.00",
        "size": "28cm*18cm*4.5cm",
        "pprice": "428.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/moguiqiaokeli\/Q0201",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }, {
        "id": 11239,
        "sku": "q0205",
        "ahead": "提前5小时预定",
        "edible": "12-20人食",
        "spec": "5磅",
        "price": "728.00",
        "size": "36cm*22cm*5cm",
        "pprice": "728.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/moguiqiaokeli\/Q0201",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }]
    }, {
      "id": "10856",
      "twoId": 10855,
      "name": "约瑟芬玫瑰",
      "french": "Joséphine",
      "price": "398.00",
      "tid": 0,
      "tname": "",
      "timg": "",
      "chineseBrief": "见证无数情侣最甜蜜的一刻，从舌尖蔓延到心间的感动，今生今世唯一爱恋",
      "fid": "37",
      "fname": "巧克力",
      "saleTotal": 8841,
      "pprice": "398.00",
      "img": "https:\/\/static.mcake.com\/goods\/yuesefenmeigui\/T0399\/list\/1.jpg",
      "sku": "T0399",
      "spec": "约2磅",
      "limg": "https:\/\/static.mcake.com\/withwheat\/list\/T0399.jpg",
      "list": [{
        "id": 10856,
        "sku": "T0399",
        "ahead": "提前5小时预定",
        "edible": "",
        "spec": "约2磅",
        "price": "398.00",
        "size": "",
        "pprice": "398.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/yuesefenmeigui\/T0399",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }]
    }, {
      "id": "11189",
      "twoId": 11187,
      "name": "百利派对",
      "french": "Soirée Bailay’s",
      "price": "298.00",
      "tid": 0,
      "tname": "",
      "timg": "",
      "chineseBrief": "来一场百利私享派对\n奶油和威士忌的美妙融合，再加一点比利时白巧克力\n感受着丝般顺滑的口感，分享与闺蜜专属的时间",
      "fid": "37",
      "fname": "巧克力",
      "saleTotal": 4200,
      "pprice": "298.00",
      "img": "https:\/\/static.mcake.com\/goods\/bailipaidui\/J0401\/list\/1.jpg",
      "sku": "J0402",
      "spec": "2磅",
      "limg": "https:\/\/static.mcake.com\/withwheat\/list\/J0402.jpg",
      "list": [{
        "id": 11188,
        "sku": "J0401",
        "ahead": "提前5小时预定",
        "edible": "2-3人食",
        "spec": "1磅",
        "price": "198.00",
        "size": "16cm*10cm*5cm",
        "pprice": "198.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/bailipaidui\/J0401",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }, {
        "id": 11189,
        "sku": "J0402",
        "ahead": "提前5小时预定",
        "edible": "4-7人食",
        "spec": "2磅",
        "price": "298.00",
        "size": "23cm*14cm*5cm",
        "pprice": "298.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/bailipaidui\/J0401",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }, {
        "id": 11190,
        "sku": "J0403",
        "ahead": "提前5小时预定",
        "edible": "8-12人食",
        "spec": "3磅",
        "price": "428.00",
        "size": "28cm*18cm*5cm",
        "pprice": "428.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/bailipaidui\/J0401",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }, {
        "id": 11191,
        "sku": "J0405",
        "ahead": "提前5小时预定",
        "edible": "12-20人食",
        "spec": "5磅",
        "price": "728.00",
        "size": "36cm*26cm*5cm",
        "pprice": "728.00",
        "pic": {
          "url": "https:\/\/static.mcake.com\/goods\/bailipaidui\/J0401",
          "list": [{
            "b": "\/big\/1.jpg",
            "m": "\/middle\/1.jpg",
            "s": "\/small\/1.jpg"
          }, {
            "b": "\/big\/2.jpg",
            "m": "\/middle\/2.jpg",
            "s": "\/small\/2.jpg"
          }, {
            "b": "\/big\/3.jpg",
            "m": "\/middle\/3.jpg",
            "s": "\/small\/3.jpg"
          }]
        }
      }]
    }]
  }
}